blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/Professional-Advantage-SDG/MarkDownViewer-releases
    about: Check the README for system requirements and download instructions.
